# If you have just installed, you can run this file accordingly.
# But this is for development purposes only.

default:
    just --list

# Following https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html

init:
    #!/usr/bin/env bash
    yes|conda create -n jupyterlab-ext --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab=4 nodejs=20 git copier=9 jinja2-time
    conda init
    source ~/.bashprofile
    conda activate jupyterlab-ext
    copier copy --trust https://github.com/jupyterlab/extension-template .

install:
    pip install -e "." 
